[package]
name = "vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.11"
backtrace-on-stack-overflow = "0.3.0"
lasso = "0.7.2"
lazy_static = "1.4.0"
rand = "0.8.5"
