[package]
name = "some-lispy-lang-rs"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "repl"
path = "src/repl.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
