[package]
name = "lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.11"
sha2 = "0.10.8"
intmap = "2.0.0"
bitflags = "2.6.0"
lazy_static = "1.4.0"

